name: Lint

on:
  # Update on pushes to main
  push:
    branches: [ "main" ]

  pull_request:

  # Allow running workflow manually
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build documentation
        run: |
          chmod +x ./gradlew
          ./gradlew lintKotlin
